In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


#Dimensions in Arrays

##0-D Arrays

In [ ]:
import numpy as np
arr=np.array(42)
print(arr)

42


##1-D Arrays

In [ ]:
from ast import AnnAssign
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


##2-D Arrays

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##3-D Arrays

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions: ',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


#Array Indexing

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[4])

5


## Access 2-D arrays

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,4])
print(arr[1,4])

5
10


##Access 3-D arrays

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,1])

8


# Negative Indexing

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,-4])

2


#Array Slicing

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[5:])

[6 7]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


##Negative Slicing

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


##Step

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


##Slicing 2-D Arrays

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1:2,3])

[9]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,4])

[5]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,0:11])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr[1,0:2,1:4])

[[2 3]
 [5 6]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr[0,0,0])

1


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,0:2,0:2])

[[1 2]
 [4 5]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0:2,0:2])

[[ 7  8]
 [10 11]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,1])

8


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0:2,1])

[ 8 11]


#NumPy DataTypes

In [ ]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [ ]:
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
arr=np.array(['a','2','3'],dtype='i')  #This will be raise error
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


#Numpy Array shape

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('Shape of array: ',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array:  (1, 1, 1, 1, 4)


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


#Numpy Array Iterating

In [ ]:
arr=np.array([1,2,3,4])
for x in arr:
  print(x)

1
2
3
4


##Iterating 2-D Arrays

In [ ]:
arr=np.array([[1,2,3,],[4,5,6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


##Iterating 3-D Arrays

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
1
2
3
4
5
6


##Iterating Array using nditer()

In [ ]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


##Iterating Array with Different DataTypes

In [ ]:
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


##Iteating with Different step size

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


##Enumerated iteration using ndenumerate()

In [ ]:
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#NumPy Joining Array

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#join two 2-D arrays along rows(axis=1):
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


###Joining arrays using stack()

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


##Stacking along Rows

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


##Stacking along Columns

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


##Stacking along Height(depth)

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


#NumPy splitting Array

In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


##Split into Arrays

In [ ]:
#Access the splitted arrays:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


##Splitting 2-D Arrays

In [ ]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Split the 2-D arrys into three 2-D arrays:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#Split the 2-D array into three 2-d arrays along rows:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


#NumPy searching arrays

In [ ]:
 #find the indexes where the value is 4:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
#find the indexes where the values are Even:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)


(array([1, 3, 5, 7]),)


In [ ]:
#find the indexes where the value Odd:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6]),)


##Search Sorted

In [ ]:
#find the indexes are the alue 7 should  be inserted:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

1


##search from the Right side

In [ ]:
#find the indexes where the value 7 should be inserted,starting from the right:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

2


##Multiple values

In [ ]:
#find the indexes where the values 2,4 and 6 should be inserted:
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


#Number sorting arrays

In [ ]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
#sort the array alphabetically:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#sort a boolean array:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


##Sorting a 2-D array

In [ ]:
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#Numpy filter array

In [ ]:
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


##Creating the filter array

In [ ]:
#Create a filter array that will return only values higher than 42:
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
  if element>42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
#create a filter array that will return only even elements from the original array:
arr=np.array([1,2,3,4,5,6,7])
filter_arr=[]
for element in arr:
  if element % 2 ==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


##Creatin filter directly from array

In [ ]:
# create a filter array that will return only values higher than 42:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
# create a filter array that will return only even elements fron the original array:
arr=np.array([1,2,3,4,5,6,7])
filter_arr=arr % 2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


#Random Numbers in NumPy

In [ ]:
#generate a random inter from 0 to 100:
from numpy import random
x=random.randint(100)
print(x)

37


In [ ]:
# generate a random float from 0 to 1:
x=random.rand()
print(x)

0.23499641631149504


##Generate Random Array

In [ ]:
# generate  1-D array containing 5 random integers from 0 to 100:
x=random.randint(100,size=(5))
print(x)

[43 62 94 42 31]


In [ ]:
# generate 2-D array with 3 rows ,each row containing 5 random integers from 0 to 100:
x=random.randint(100,size=(3,5))
print(x)

[[27 93 16 51 42]
 [83 89 12 62 10]
 [ 2  0 29 79 48]]


In [ ]:
# generate a 1-D array containing 5 random floats:
x=random.rand(5)
print(x)

[0.1242079  0.50049799 0.68615478 0.16846408 0.76177668]


In [ ]:
# generate a 2-D array with 3 rows,each containing 5 random floats:
x=random.rand(3,5)
print(x)

[[0.58168408 0.67044311 0.9070981  0.7422511  0.21457595]
 [0.17805201 0.27466551 0.02686379 0.82342449 0.24658838]
 [0.87876808 0.3467306  0.4793116  0.4620364  0.23797013]]


##Choice()

In [ ]:
# return one of the values in array:
x=random.choice([3,5,7,9])
print(x)

3


In [ ]:
# generate a 2-D array that consist of the values in the array parameter(3,5,7 and 9):
x=random.choice([3,5,7,9],size=(3,5))
print(x)

[[5 9 3 3 7]
 [3 3 9 7 9]
 [5 9 5 5 3]]


#STATISTICS

In [ ]:
import numpy as np
import statistics as stats
li=np.random.randint(0,100,10)
print(li)
print("Mean: ",np.mean(li))
print("Median: ",np.median(li))
print("Mode: ",stats.mode(li))

[16 89 51  0 49 23 46 38 32 88]
Mean:  43.2
Median:  42.0
Mode:  16


#InterQuartile Range(IQR)

In [ ]:
import numpy as np
import scipy.stats as stats

data=[12,15,14,10,18,20,22,25,14,17]

range_value=max(data)-min(data)
print(f"Range:{range_value}")

Range:15


In [ ]:
variance_value=np.var(data,ddof=0)
sample_variance_value=np.var(data,ddof=1)
print(f"population variance:{variance_value}")
print(f"sample variance:{sample_variance_value}")

population variance:19.410000000000004
sample variance:21.56666666666667


In [ ]:
std_dev_value=np.std(data,ddof=0)
sample_std_dev_value=np.std(data,ddof=1)
print(f"population standard deviation:{std_dev_value}")
print(f"sample standard deviation:{sample_std_dev_value}")

population standard deviation:4.405678154382138
sample standard deviation:4.643992535164831


In [ ]:
Q1=np.percentile(data,25)
Q3=np.percentile(data,75)
iqr_value=Q3-Q1
print(f"Interquartile Range(IQR):{iqr_value}")

Interquartile Range(IQR):5.5
